### ISSUE TITLE
ValueError: No variables to save

### ISSUE THREAD

**Issue by devinzkx123** [duxy-me/AMR#4]
Traceback (most recent call last):
  File "/home/recommendation/AMR/src/main.py", line 33, in <module>
    s = Solver(args)
  File "/home/recommendation/AMR/src/solver/Solver.py", line 21, in __init__
    self.saver = tf.train.Saver(tf.trainable_variables(), max_to_keep=0)
  File "/home/.local/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 919, in __init__
    self.build()
  File "/home/.local/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 931, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/.local/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 956, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

进程已结束,退出代码1

**Comment by devinzkx123** [comment]
starting common Solver
self.emb_image (4998, 2048) self.pos.size 6618 self.neg.size 3226
size (3226, 4998)
model None
2022-04-30 11:04:26.888658: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.888815: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.888939: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889060: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889179: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889297: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889415: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889533: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-04-30 11:04:26.889567: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-04-30 11:04:26.890587: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by devinzkx123** [comment]
执行的过程：
non-resource variables are not supported in the long term
Namespace(dataset='/home/recommendation/AMR/data/pinterest', model='AMR', emb1_K=64, batch_size=4096, lr='0.01', verbose=50, epoch=500, regs='0.000001', lmd=1, keep_prob=0.6, adv=False, adv_type='grad', cnn='resnet', epsilon=2, weight_dir='./weights')
starting common Solver
self.emb_image (4998, 2048) self.pos.size 6618 self.neg.size 3226
size (3226, 4998)
model None
2022-04-30 11:12:09.326163: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326334: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326461: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326581: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326697: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326813: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.326948: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.327068: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2022-04-30 11:12:09.327099: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-04-30 11:12:09.328472: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by devinzkx123** [comment]
Traceback (most recent call last):
  File "/home/zkx/recommendation/AMR/src/main.py", line 35, in <module>
    s.train()                
  File "/home/zkx/recommendation/AMR/src/solver/Solver.py", line 51, in train
    self.test('epoch %d' % i)
  File "/home/zkx/recommendation/AMR/src/solver/Solver.py", line 81, in test
    score5 = np.mean(map(self._score, zip(d,[5] * len(d))), 0)    
  File "<__array_function__ internals>", line 5, in mean
  File "/usr/local/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3419, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/usr/local/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 166, in _mean
    rcount = _count_reduce_items(arr, axis, keepdims=keepdims, where=where)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 75, in _count_reduce_items
    items *= arr.shape[mu.normalize_axis_index(ax, arr.ndim)]
numpy.AxisError: axis 0 is out of bounds for array of dimension 0

进程已结束,退出代码1
